version: "3"
services:
       expense-tracker:
           container_name: expense-tracker
           image: latest/expense-tracker
           environment: 
              NODE_ENV: ${NODE_ENV}
              BASE_URL: ${BASE_URL}
              PORT: ${PORT}
              MONGO_URL: ${MONGO_URL}

           restart: always
           build: .
           ports:
             - "4000:4000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27018:27017'